spec:
  template:
    spec:
      containers:
        -
          resources:
            requests:
              cpu: "0.1"
              memory: 64Mi
            limits:
              cpu: "0.1"
              memory: 64Mi
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
          ports:
            - containerPort: 8162
              name: http
              protocol: TCP
            - containerPort: 9992
              name: health
              protocol: TCP
