server:
  port: 8162

springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "hawtio, jolokia, httptrace"
  endpoint:
    httptrace:
      enabled: true
